---
title: "Air concentration analysis for hourly values"
author: "Paige Varner"
date: "2024-06-10"
output: html_document
---



#load libraries and data
```{r}
library("dplyr")
library("bigrquery")
library("DBI")
library("pheatmap")
library("RColorBrewer")
library("Rmisc")
library("stats")
library("rstatix")
library("ggplot2")
library("tidyr")
library("car")
library("janitor")
library("dunn.test")
library("sf")
detach(package:Rmisc)
detach(package:plyr)

ozone = read.csv("~/CO_CRA/CO_CRA/Data/ozone_hourly_2018-2023.csv")
all = read.csv("~/CO_CRA/CO_CRA/Data/hourly_VOCs.csv")
```


#fix and format data
```{r}
#fix chemical columns and their names, and filter for chemicals we're looking at
all$Xylenes = all$o.Xylene + all$m..and.p.Xylene
colnames(all)[colnames(all) == "C2Cl4"] = "PCE"
colnames(all)[colnames(all) == "C2HCl3"] = "TCE"

#add chemical concentrations together for aliphatic low and aromatic medium groups
all$Aliphatic_low = NA

all$Aliphatic_low = all$n.Octane + all$i.Pentane + all$n.Pentane + all$trans_2.Pentene + all$X1.Pentene + all$cis.2.Pentene + all$n.Hexane + all$Isoprene + all$X2.4.Dimethylpentane + all$n.Heptane + all$Cyclohexane + all$X2.3.Dimethylpentane + all$X2.Methylhexane + all$X3.Methylhexane + all$X2.2.4.Trimethylpentane + all$Methylcyclohexane + all$X2.3.4.Trimethylpentane + all$X2.Methylheptane + all$X3.Methylheptane + all$Cyclopentane

all$Aromatic_medium = all$i.Propylbenzene + all$n.Propylbenzene + all$X3.Ethyltoluene + all$X4.Ethyltoluene + all$X1.3.5.Trimethylbenzene + all$X2.Ethyltoluene + all$X1.2.4.Trimethylbenzene + all$X1.2.3.Trimethylbenzene + all$X1.3.Diethylbenzene + all$X1.4.Diethylbenzene

all_clean = all %>%
  select(Sampling.Site, Phase, Benzene, Toluene, Ethylbenzene, Xylenes, n.Nonane, n.Decane, Aliphatic_low, Aromatic_medium, Styrene, TCE, PCE, Propene)

#transform to long for graphing and analysis
all_long = all_clean %>%
  pivot_longer(cols = c("Benzene", "Toluene", "Ethylbenzene", "Xylenes", "n.Nonane", "n.Decane", "Aliphatic_low", "Aromatic_medium", "Styrene", "TCE", "PCE", "Propene"), names_to = "Chemical", values_to = "Value") 

#order phases and chemicals for best graphing
all_long$Phase = factor(all_long$Phase, levels = c("Drilling", "pre", "prod"))

all_long$Chemical = factor(all_long$Chemical, levels = c("Benzene", "Toluene", "Ethylbenzene", "Xylenes", "Styrene", "n.Nonane", "n.Decane",  "TCE", "PCE", "Propene", "Aliphatic_low", "Aromatic_medium"))
```



#dot plot for phase of O&G on the x axis (for O&G sites only)
```{r}
#select data for pad locations only 
pads = all_long %>%
  filter(Sampling.Site == "Interchange" | Sampling.Site == "Livingston" | Sampling.Site == "Northwest" | Sampling.Site == "United")

pads$Phase <- factor(pads$Phase, levels = c("Drilling", "pre", "prod"))

medians <- pads %>%
  group_by(Chemical, Phase) %>%
  summarize(median_value= median(Value, na.rm = TRUE), .groups = 'drop')

VOCs_dotplot <- ggplot(pads, aes(x = Phase, y = Value, fill = Sampling.Site)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.7, stroke = 0) +  # Make the outline the same color as the fill
  scale_fill_manual(values = c("Interchange" = "blue", "Livingston" = "red", "Northwest" = "violet", "United" = "yellow")) + 
  geom_crossbar(data = medians, aes(x = Phase, y = median_value, ymin = median_value, ymax = median_value), inherit.aes = FALSE, color = "black", width = 0.5) +  # Add black line for median
  theme_bw() +
  ylab("Concentration (ppb)") +
  xlab("Phase") +
  facet_wrap(~ Chemical, scales = "free", ncol = 4, nrow = 3) +
  scale_x_discrete(labels = c("Drilling" = "Drilling", "pre" = "Pre-prod.", "prod" = "Prod.")) +
  theme(legend.position = "right",
        strip.text = element_text(size = 14),
        axis.text.x = element_text(size = 14, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 14),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 16),
        plot.title = element_text(size = 18))

VOCs_dotplot

ggsave(filename = "VOCs_dotplot_phase_hourly.png", device = "png", plot = VOCs_dotplot, path = "~/CO_CRA/CO_CRA/Output/Air_Data/Hourly", width = 13, height = 10)

```




## descriptive statistics tables ##

#add ozone to include in tables
```{r}
#convert date columns to date class
all$Date <- as.Date(all$Date)
ozone$Date.Local <- as.Date(ozone$Date.Local)

# Extract the hour from the Time columns
all <- all %>%
  mutate(Hour = format(as.POSIXct(Time, format = "%H:%M"), "%H"))

ozone <- ozone %>%
  mutate(Hour = format(as.POSIXct(Time.Local, format = "%H:%M"), "%H"))

# Merge the dataframes on Date and Hour
ozone_selected <- ozone %>%
  select(Date.Local, Hour, Sample.Measurement) %>%
  rename(Ozone = Sample.Measurement) %>%  # Rename the column
  mutate(Ozone = Ozone * 1000)

merged_df <- all %>%
  left_join(ozone_selected, by = c("Date" = "Date.Local", "Hour"))

```


#summary stats by site type (community, O&G)
```{r}

# Create the Site_Type column
merged_df <- merged_df %>%
  mutate(Site_Type = case_when(
    Sampling.Site %in% c("Northwest", "Interchange", "United", "Livingston") ~ "O&G Sites",
    Sampling.Site %in% c("Anthem", "Soaring Eagle") ~ "Community Sites",
    TRUE ~ "Other"
  )) %>%
  filter(Site_Type != "Other")

# Calculate summary statistics
summary_stats <- merged_df %>%
  group_by(Site_Type) %>%
  summarize(across(where(is.numeric), list(
    n = ~ sum(!is.na(.)),
    min = ~ min(., na.rm = TRUE),
    mean = ~ mean(., na.rm = TRUE),
    median = ~ median(., na.rm = TRUE),
    max = ~ max(., na.rm = TRUE),
    sd = ~ sd(., na.rm = TRUE),
    se = ~ sd(., na.rm = TRUE) / sqrt(sum(!is.na(.)))
  ), .names = "{.col}_{.fn}"))

# Reshape the dataframe to the desired format
reshaped_stats <- summary_stats %>%
  pivot_longer(
    cols = -Site_Type,
    names_to = "Chemical_Statistic",
    values_to = "Value"
  ) %>%
  separate(Chemical_Statistic, into = c("Chemical", "Statistic"), sep = "_(?=[^_]+$)") %>%
  pivot_wider(
    names_from = c(Site_Type, Statistic),
    values_from = Value,
    names_glue = "{Site_Type}_{Statistic}"
  )

#save as csv
write.csv(reshaped_stats, file = "~/CO_CRA/CO_CRA/Output/Air_Data/Hourly/hourly_summary_stats_type.csv")

```



#summary stats by phase
```{r}
# Calculate summary statistics grouped by Phase
summary_stats_phase <- merged_df %>%
  group_by(Phase) %>%
  summarize(across(where(is.numeric), list(
    n = ~ sum(!is.na(.)),
    min = ~ min(., na.rm = TRUE),
    mean = ~ mean(., na.rm = TRUE),
    median = ~ median(., na.rm = TRUE),
    max = ~ max(., na.rm = TRUE),
    sd = ~ sd(., na.rm = TRUE),
    se = ~ sd(., na.rm = TRUE) / sqrt(sum(!is.na(.)))
  ), .names = "{.col}_{.fn}"))

# Reshape the dataframe to the desired format
reshaped_stats_phase <- summary_stats_phase %>%
  pivot_longer(
    cols = -Phase,
    names_to = "Chemical_Statistic",
    values_to = "Value"
  ) %>%
  separate(Chemical_Statistic, into = c("Chemical", "Statistic"), sep = "_(?=[^_]+$)") %>%
  pivot_wider(
    names_from = c(Phase, Statistic),
    values_from = Value,
    names_glue = "{Phase}_{Statistic}"
  )

#save as csv
write.csv(reshaped_stats_phase, file = "~/CO_CRA/CO_CRA/Output/Air_Data/Hourly/hourly_summary_stats_phase.csv")

```


















